spring.application.name=job-service

server.port=8082

jwt.secret.key=2f3768301ec01b98b0769415010cd81b12e1692c32d4aad7065f6b424b5150b3
#JWT expiratoin time in msec (30 minutes)
jwt.expiration.time=1800000

spring.datasource.url=jdbc:mysql://localhost:3306/talenthire_job_db
spring.datasource.username=root
spring.datasource.password=neema
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true