spring.application.name=api-gateway


jwt.secret.key=2f3768301ec01b98b0769415010cd81b12e1692c32d4aad7065f6b424b5150b3
#JWT expiratoin time in msec (30 minutes)
jwt.expiration.time=1800000

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=job-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/job/**
